#!/bin/sh

set -o errexit
set -o nounset

# check if we have a bands database file in the app repository folder
# if we do not, create one in the current directory
DB_FILE=app/database/bands.db
if test -f "$DB_FILE"; then
  echo "$DB_FILE exists."
else
  python3.9 app/scripts/create_populate_db.py
  mv bands.db app/database/bands.db
  echo "created $DB_FILE"
fi

# run the ASGI server
uvicorn app.main:app --reload --host '0.0.0.0' --port '8000'