name: discogs puller

on: [push]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  DISCOGS_PERSONAL_ACCESS_TOKEN: ${{ secrets.DISCOGS_PERSONAL_ACCESS_TOKEN }}
  DISCOGS_ARTIST_ID: ${{ secrets.DISCOGS_ARTIST_ID }}
  DB_URL: ${{ secrets.DB_URL }}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Testing
        run: |
          pytest

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only >
        --build-arg DISC_TOKEN=$DISCOGS_PERSONAL_ACCESS_TOKEN
        --build-arg ARTIST=$DISCOGS_ARTIST_ID
        --build-arg DEBUG=False
        --build-arg DB=$DB_URL
